import one from "../assets/icons/1.png";
import two from "../assets/icons/2.png";
import three from "../assets/icons/3.png";
import four from "../assets/icons/4.png";
import five from "../assets/icons/5.png";
import six from "../assets/icons/6.png";
import seven from "../assets/icons/7.png";
import eight from "../assets/icons/8.png";
import nine from "../assets/icons/9.png";
import ten from "../assets/icons/10.png";
import A from "../assets/icons/A.png";
import logo from "../assets/icons/Logo.png";
import php from "../assets/icons/php.png";
import java from "../assets/icons/java.png";
import live from "../assets/icons/live.png";
import play from "../assets/icons/play.png";
import html5 from "../assets/icons/html5.png";
import audio from "../assets/icons/audio.png";
import blocks from "../assets/icons/blocks.png";
import courses from "../assets/icons/courses.svg";
import present from "../assets/icons/present.png";
import hero_bg from "../assets/icons/BG_right.png";
import home from "../assets/icons/studentHome.svg";
import price_tag from "../assets/icons/price-tag.png";
import lightbulb from "../assets/icons/lightbulb.png";
import avatar from "../assets/icons/default_avatar.png";
import settings from "../assets/icons/settings.svg";
import profile from "../assets/icons/profile.svg";
import tutors from "../assets/icons/tutors.svg";
import assessment from "../assets/icons/tutors.svg";
import logout from "../assets/icons/logout.svg";
import Tropy1 from "../assets/icons/Tropy1.png";
import Tropy2 from "../assets/icons/Tropy2.png";
import Tropy3 from "../assets/icons/Tropy3.png";
import Tropy4 from "../assets/icons/Tropy4.png";
import ProfileIcon from "../assets/icons/ProfileIcon.png";
import InviteIcon from "../assets/icons/InviteIcon.png";
import DeleteIcon from "../assets/icons/DeleteIcon.png";
import ProfileFoto from "../assets/icons/ProfileFoto.png";
import Camera from "../assets/icons/Camera.svg";
import Academic from "../assets/icons/academic-cap.svg";
import Assessment from "../assets/icons/assessment.svg";
import AcademicLight from "../assets/icons/academic-cap-light.svg";
import Notification from "../assets/icons/notifcation.svg";

export const _A = A;
export const ONE = one;
export const TWO = two;
export const SIX = six;
export const PHP = php;
export const TEN = ten;
export const FOUR = four;
export const NINE = nine;
export const FIVE = five;
export const JAVA = java;
export const HOME = home;
export const SEVEN = seven;
export const EIGHT = eight;
export const HTML5 = html5;
export const THREE = three;
export const BLOCKS = blocks;
export const HERO_BG = hero_bg;
export const COURSES = courses;
export const PRESENT = present;
export const PRICE_TAG = price_tag;
export const LIGHTBULB = lightbulb;
export const SETTINGS = settings;
export const PROFILE = profile;
export const TUTORS = tutors;
export const LOGOUT = logout;
export const ASSESSMENT = assessment;
export const LOGO = logo;
export const AUDIO = audio;
export const LIVE = live;
export const PLAY = play;
export const AVATAR = avatar;
export const TROPY1 = Tropy1;
export const TROPY2 = Tropy2;
export const TROPY3 = Tropy3;
export const TROPY4 = Tropy4;
export const PROFILEICON = ProfileIcon;
export const INVITEICON = InviteIcon;
export const DELETEICON = DeleteIcon;
export const PROFILEFOTO = ProfileFoto;
export const CAMERA = Camera;
export const ACADEMIC_CAP = Academic;
export const ACADEMIC_LIGHT = AcademicLight;
export const _ASSESSMENT = Assessment;
export const NOTIFICATION = Notification;
