import one from "../assets/icons/1.png";
import two from "../assets/icons/2.png";
import three from "../assets/icons/3.png";
import four from "../assets/icons/4.png";
import five from "../assets/icons/5.png";
import six from "../assets/icons/6.png";
import seven from "../assets/icons/7.png";
import eight from "../assets/icons/8.png";
import nine from "../assets/icons/9.png";
import ten from "../assets/icons/10.png";
import A from "../assets/icons/A.png";
import blocks from "../assets/icons/blocks.png";
import hero_bg from "../assets/icons/BG_right.png";
import logo from "../assets/icons/Logo.png";
import html5 from "../assets/icons/html5.png";
import php from "../assets/icons/php.png";
import present from "../assets/icons/present.png";
import price_tag from "../assets/icons/price-tag.png";
import java from "../assets/icons/java.png";
import lightbulb from "../assets/icons/lightbulb.png";
import audio from "../assets/icons/audio.png";
import live from "../assets/icons/live.png";
import play from "../assets/icons/play.png";
import avatar from "../assets/icons/default_avatar.png";
import Tropy1 from "../assets/icons/Tropy1.png";
import Tropy2 from "../assets/icons/Tropy2.png";
import Tropy3 from "../assets/icons/Tropy3.png";
import Tropy4 from "../assets/icons/Tropy4.png";
import Profile from "../assets/icons/ProfileIcon.png";
import InviteIcon from "../assets/icons/InviteIcon.png";
import DeleteIcon from "../assets/icons/DeleteIcon.png";
import ProfileFoto from "../assets/icons/ProfileFoto.png";

export const ONE = one;
export const TWO = two;
export const THREE = three;
export const FOUR = four;
export const FIVE = five;
export const SIX = six;
export const SEVEN = seven;
export const EIGHT = eight;
export const NINE = nine;
export const TEN = ten;
export const _A = A;
export const BLOCKS = blocks;
export const HERO_BG = hero_bg;
export const HTML5 = html5;
export const PHP = php;
export const PRESENT = present;
export const PRICE_TAG = price_tag;
export const JAVA = java;
export const LIGHTBULB = lightbulb;
export const LOGO = logo;
export const AUDIO = audio;
export const LIVE = live;
export const PLAY = play;
export const AVATAR = avatar;
export const TROPY1 = Tropy1;
export const TROPY2 = Tropy2;
export const TROPY3 = Tropy3;
export const TROPY4 = Tropy4;
export const PROFILE = Profile;
export const INVITEICON = InviteIcon;
export const DELETEICON = DeleteIcon;
export const PROFILEFOTO = ProfileFoto;
