import auth from "../assets/illustrations/auth.svg";
import video from "../assets/illustrations/video.jpg";
import pricing from "../assets/illustrations/pricing.svg";
import pattern from "../assets/illustrations/Pattern_1.png";
import hero_right from "../assets/illustrations/hero_right.png";
import college_hero from "../assets/illustrations/college_hero.png";
import college_pattern from "../assets/illustrations/college_pattern.png";
import career from "../assets/illustrations/career.png";
import courses from "../assets/illustrations/courses.png";
import privacy_p_illustration from "../assets/illustrations/privacy_p_illustration.png";
import collabration from "../assets/illustrations/collabration.jpg";
import excel from "../assets/illustrations/excel.jpg";
import graduate from "../assets/illustrations/graduate.jpg";
import remote from "../assets/illustrations/remote.jpg";

export const AUTH = auth;
export const VIDEO = video;
export const CAREER = career;
export const PATTERN = pattern;
export const COURSES = courses;
export const HERO = hero_right;
export const PRICING = pricing;
export const COLLEGE_HERO = college_hero;
export const COLLEGE_PATTERN = college_pattern;
export const PRIVACY_P_ILLUSTRATION = privacy_p_illustration;
export const COLLABRATION = collabration;
export const EXCEL = excel;
export const GRADUATE = graduate;
export const REMOTE = remote;
