import pnf from "../assets/illustrations/404.png";
import video from "../assets/illustrations/video.jpg";
import excel from "../assets/illustrations/excel.png";
import tutor from "../assets/illustrations/tutor.png";
import login from "../assets/illustrations/login.svg";
import remote from "../assets/illustrations/remote.png";
import career from "../assets/illustrations/career.png";
import signup from "../assets/illustrations/signup.svg";
import pricing from "../assets/illustrations/pricing.svg";
import courses from "../assets/illustrations/courses.png";
import good_pricing from "../assets/illustrations/pricing.png";
import graduate from "../assets/illustrations/graduate.png";
import pattern from "../assets/illustrations/Pattern_1.png";
import hero_right from "../assets/illustrations/hero_right.png";
import apply_tutor from "../assets/illustrations/apply-tutor.png";
import college_hero from "../assets/illustrations/college_hero.png";
import collaboration from "../assets/illustrations/collaboration.png";
import college_pattern from "../assets/illustrations/college_pattern.png";
import privacy_p from "../assets/illustrations/privacy_p_illustration.png";

export const PNF = pnf;
export const LOGIN = login;
export const TUTOR = tutor;
export const VIDEO = video;
export const EXCEL = excel;
export const REMOTE = remote;
export const SIGNUP = signup;
export const CAREER = career;
export const PATTERN = pattern;
export const COURSES = courses;
export const HERO = hero_right;
export const PRICING = pricing;
export const GRADUATE = graduate;
export const APPLY_TUTOR = apply_tutor;
export const COLLEGE_HERO = college_hero;
export const GOOD_PRICING = good_pricing;
export const COLLABORATION = collaboration;
export const COLLEGE_PATTERN = college_pattern;
export const PRIVACY_P_ILLUSTRATION = privacy_p;
